# Generated by Django 5.2 on 2025-05-28 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Ты долбоёб? Вводи дату как дд.мм.гггг --:--!', regex='^\\d{2}\\.\\d{2}\\.\\d{4} --:--$')], verbose_name='Дата (дд.мм.гггг --:--)')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('budget_type', models.CharField(choices=[('solo', 'Соло'), ('group', 'Групповой')], default='solo', max_length=20, verbose_name='Тип бюджета')),
                ('venue_type', models.CharField(choices=[('own', 'Своё'), ('rented', 'Аренда')], default='own', max_length=20, verbose_name='Место проведения')),
                ('venue_cost', models.IntegerField(default=0, verbose_name='Стоимость Аренды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-created_at'],
            },
        ),
    ]
