# Generated by Django 5.2 on 2025-05-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='budget_type',
            field=models.CharField(choices=[('Group', 'Групповой'), ('Solo', 'Соло')], default='fixed', max_length=20, verbose_name='Тип бюджета'),
        ),
    ]
