# Generated by Django 5.2 on 2025-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_venue_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='budget_type',
            field=models.CharField(choices=[('SOLO', 'Соло'), ('GROUP', 'Групповой')], default='solo', max_length=20, verbose_name='Тип бюджета'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_type',
            field=models.CharField(choices=[('OWN', 'Своё'), ('RENTED', 'Аренда')], default='own', max_length=20, verbose_name='Место проведения'),
        ),
    ]
