# Generated by Django 5.2 on 2025-05-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_budget_type_alter_event_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text='Формат: YYYY-MM-DDTHH:MM', verbose_name='Дата мероприятия'),
        ),
    ]
