# Generated by Django 5.2 on 2025-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_cost',
            field=models.IntegerField(default=None, verbose_name='Стоимость Аренды'),
        ),
    ]
