# Generated by Django 5.2 on 2025-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_budget_type_alter_event_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость Аренды'),
        ),
    ]
