# Generated by Django 5.2 on 2025-05-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_venue_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_cost',
            field=models.CharField(default=None, verbose_name='Стоимость Аренды'),
        ),
    ]
