# Generated by Django 5.2 on 2025-05-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_venue_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_cost',
            field=models.CharField(blank=True, default=0, null=True, verbose_name='Стоимость Аренды'),
        ),
    ]
