# Generated by Django 5.2 on 2025-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_venue_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='guests_count',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Число гостей'),
        ),
    ]
