# Generated by Django 5.2 on 2025-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_description_event_guests_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='guests_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Число гостей'),
        ),
    ]
