# Generated by Django 5.2 on 2025-06-02 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_description_alter_event_guests_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('quntity_per_person', models.FloatField(verbose_name='Кол-во на человека')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='events.event', verbose_name='Мероприятие')),
            ],
        ),
    ]
