# Generated by Django 5.2 on 2025-06-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='quntity_per_person',
            new_name='quantity_per_person',
        ),
    ]
