# Generated by Django 5.2 on 2025-06-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_rename_quntity_per_person_menu_quantity_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='purchases_overall',
            field=models.FloatField(blank=True, null=True, verbose_name='За покупки общая сумма'),
        ),
        migrations.AddField(
            model_name='event',
            name='purchases_per_person',
            field=models.FloatField(blank=True, null=True, verbose_name='За покупки с чел.'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_overall',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая общая сумма'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_per_person',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая за чел.'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_overall',
            field=models.FloatField(blank=True, null=True, verbose_name='За помещение общая сумма'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_per_person',
            field=models.FloatField(blank=True, null=True, verbose_name='За помещение с чел.'),
        ),
    ]
