# Generated by Django 5.2 on 2025-06-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_purchases_overall_event_purchases_per_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
