# Generated by Django 5.2 on 2025-06-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_event_budget_type_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_menu_selection',
            field=models.BooleanField(default=False, verbose_name='Разрешить выбор меню'),
        ),
        migrations.AddField(
            model_name='event',
            name='poll_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания опроса'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('telegram_id', models.CharField(max_length=100, verbose_name='Telegram ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'unique_together': {('event', 'telegram_id')},
            },
        ),
    ]
